name: Create and deploy to Azure App Services

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.PAT }}
                  ref: main

            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: '18.x'

            - name: npm install, build, and test
              run: |
                  cd client
                  npm install
                  npm run build
                  cd ../
                  mv server/* .
                  rmdir server
              env:
                  CI: ''
            # Zip the build directory
            - name: Zip Release
              uses: TheDoctor0/zip-release@0.6.2
              with:
                  filename: release.zip
                  exclusions: '*.git* .editorconfig /*client/* *.github* */node_modules/*'

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v2
              with:
                  name: node-app
                  path: release.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                  name: node-app

            - name: 'Deploy to Azure Web App'
              uses: azure/webapps-deploy@v2
              id: deploy-to-webapp
              with:
                  app-name: 'todos-to-do'
                  slot-name: 'production'
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
                  package: release.zip
